### PR TITLE
[OSD-18938] Workaround the CI failed for govulncheck

### PR DESCRIPTION
**Pull request by xiaoyu74**
### What type of PR is this?
workaround

### What does this PR do?
This PR modifies the `scan` target in the Makefile. If `govulncheck` detects any vulnerabilities, it will display a notification message but will still return a successful exit code, ensuring that the `ci/prow/scan-optional` CI job passes.

Even though `govulncheck` will continue to run, any detected vulnerabilities will be recorded in the `CI build logs`. This allows us to keep track and plan for the necessary updates to the vulnerable Go library packages at a later time.

### CODE REVIEW

**Review by supreeth7 — COMMENTED** [review]
@xiaoyu74 this is neat!
Do you want to get this merged or polish it a bit more?

**Comment by xiaoyu74** [comment]
> @xiaoyu74 this is neat! Do you want to get this merged or polish it a bit more?

@supreeth7 - Thanks for your time to review, merging this PR can definitely make the`ci/prow/scan-optional` pass  since it updates the target `scan` which tells `make` to ignore errors from `govulncheck` (it will still execute but just ignore errors)

However, this is just a temp workaround since the detected vulnerabilities still exist. What am I expecting and thought it might be better is that after using the workaround, the vulnerability info below can still be displayed from CI build logs or somewhere giving us some clues indicate that we will need to upgrade the go lib package to fix it eventually. 
```
make scan
/usr/bin/which: no podman in (/home/sbai/osd_work/google-cloud-sdk/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/usr/local/:/usr/local/bin/:/usr/local/go/bin:/home/sbai/go/bin)
govulncheck ./... 2>&1
Scanning your code and 797 packages across 113 dependent modules for known vulnerabilities...

=== Informational ===

Found 2 vulnerabilities in packages that you import, but there are no call
stacks leading to the use of these vulnerabilities. You may not need to
take any action. See https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck
for details.

Vulnerability #1: GO-2023-2043
    Improper handling of special tags within script contexts in html/template
  More info: https://pkg.go.dev/vuln/GO-2023-2043
  Standard library
    Found in: html/template@go1.19.12
    Fixed in: html/template@go1.21.1

Vulnerability #2: GO-2023-2041
    Improper handling of HTML-like comments in script contexts in html/template
  More info: https://pkg.go.dev/vuln/GO-2023-2041
  Standard library
    Found in: html/template@go1.19.12
    Fixed in: html/template@go1.21.1
    
Note: Vulnerabilities were checked, but failures are currently non-blocking.
```

So, let's hold it for some more time so I can do some more test and polish it if needed :-)

**Comment by xiaoyu74** [comment]
@supreeth7 - I updated the PR with a conditional statement. 

So basically, this PR modifies the `scan` target in the Makefile. If `govulncheck` detects any vulnerabilities, it will display a notification message but will still return a successful exit code, ensuring that the `ci/prow/scan-optional` CI job passes.

Even though `govulncheck` will continue to run, any detected vulnerabilities will be recorded in the `CI build logs`. This allows us to keep track and plan for the necessary updates to the vulnerable Go library packages at a later time for a complete fix.

**Review by supreeth7 — APPROVED** [review]
I like this, thanks @xiaoyu74.
The CI showing as failed due to a check that was optional wasn't nice., this should fix it now.

/lgtm

**Pull request merged**
