### PR TITLE
[OSD-17896] Add CI release script to test release automation

### PR DESCRIPTION
**Pull request by xiaoyu74**
### What type of PR is this?

_(feature)_

### What this PR do / Why we need it?
Test openshift-ci release automation

### JIRA Ticket: 
https://issues.redhat.com/browse/OSD-17896

### CODE REVIEW

**Comment by supreeth7** [comment]
@xiaoyu74 do we still need this PR in the queue? I see the Jira has been closed.

**Comment by xiaoyu74** [comment]
> @xiaoyu74 do we still need this PR in the queue? I see the Jira has been closed.

Hey @supreeth7 - Sorry for leaving this PR in the queue for very long. The previous task [OSD-17896](https://issues.redhat.com/browse/OSD-17896) was a SPIKE task for doing some research and documentation.

After the SPIKE task is done, I didn't get a chance to further work on the `bp-cli release` but other priorities. 
We created a new validation/testing ticket: [OSD-19314](https://issues.redhat.com/browse/OSD-19314) which I am working on for this bp-cli release task, and doing some more actual testing. 

So, it's good to leave this PR for some more time for testing or merging it since this PR is just to convert the [manual release steps](https://github.com/openshift/backplane-cli/blob/main/docs/release.md) into a bash script. 

**Notes:** The reason I left it in the queue rather than request an approval to merge is to see if we can test the semi-automatic release in my own branch rather than merging to the master, but for now, I haven't got a good approach to trigger the release to run this script in my branch.

**Comment by supreeth7** [comment]
Thanks for explaining @xiaoyu74, let it bake in the queue then :+1:

**Pull request merged**
