### PR TITLE
Update k8s dependencies

### PR DESCRIPTION
**Pull request by AlexVulaj**
### What type of PR is this?
cleanup

### What this PR does / Why we need it?
This PR updates our k8s dependencies to the latest version to remove conflicts in other apps using both the `backplane-cli` and `k8s.io/*` as dependencies.

### Special notes for your reviewer
I discovered this while trying to write an incredibly simple app for learning purposes that looked as follows:
```go
import (
	"context"
	"fmt"
	bplogin "github.com/openshift/backplane-cli/cmd/ocm-backplane/login"
	bpconfig "github.com/openshift/backplane-cli/pkg/cli/config"
	v1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func main() {
	bp, _ := bpconfig.GetBackplaneConfiguration()
	cfg, _ := bplogin.GetRestConfig(bp, "<some ID>")

	k8sClient, _ := client.New(cfg, client.Options{})

	var pods v1.PodList
	_ = k8sClient.List(context.TODO(), &pods, &client.ListOptions{Namespace: "some-namespace"})

	fmt.Println(pods.String())
}
```

When running this application, the versions of some k8s dependencies imported by backplane-cli were causing compilation issues with the dependencies used by other k8s dependencies.

### CODE REVIEW

**Comment by AlexVulaj** [comment]
Note - these builds are running into a problem here where the modules I added all require go 1.22, but go 1.22 isn't supported by our CI yet.

**Comment by xiaoyu74** [comment]
Let's hold this PR since it depends on the go version to be bumped to the version 1.22. We have an existing task https://issues.redhat.com/browse/OSD-24733 for the go version bump.

**Comment by samanthajayasinghe** [comment]
@AlexVulaj go 1.22.x support added in this [PR](https://github.com/openshift/backplane-cli/pull/554)  , you may have to rebase the PR and trigger the CI

**Pull request closed without merging**
